# site.yml
---
- hosts: pu004
  become: true
  roles: [bertvv.rh-base,bertvv.httpd,bertvv.mariadb,bertvv.wordpress]
  post_tasks:
    - name: Nat mag nooit default route zijn
      shell: nmcli connection modify eth0 ipv4.never-default yes
    - name: Default route over host only adapter instellen
      shell: nmcli connection modify System\ eth1 ipv4.routes 192.0.2.0/24 ipv4.gateway 192.0.2.254
    - name: dns uitschakelen op nat
      shell: nmcli connection modify eth0 +ipv4.ignore-auto-dns true
    - name: dns inschakelen via de router
      shell: nmcli connection modify System\ eth1 ipv4.dns "192.0.2.10 192.0.2.254"
    - name: search domein instellen
      shell: nmcli connection modify System\ eth1 ipv4.dns-search avalon.lan
    - name: Restart network service
      systemd:
       name: network.service
       state: restarted

- hosts: pu001
  become: true
  roles: [bertvv.rh-base,bertvv.bind]
  post_tasks:
    - name: Nat mag nooit default route zijn
      shell: nmcli connection modify eth0 ipv4.never-default yes
    - name: Default route over host only adapter instellen
      shell: nmcli connection modify System\ eth1 ipv4.routes 192.0.2.0/24 ipv4.gateway 192.0.2.254
    - name: dns uitschakelen op nat
      shell: nmcli connection modify eth0 +ipv4.ignore-auto-dns true
    - name: dns inschakelen via de router
      shell: nmcli connection modify System\ eth1 ipv4.dns "192.0.2.10 192.0.2.254"
    - name: search domein instellen
      shell: nmcli connection modify System\ eth1 ipv4.dns-search avalon.lan
    - name: Restart network service
      systemd:
       name: network.service
       state: restarted


- hosts: pu002
  become: true
  roles: [bertvv.rh-base,bertvv.bind]
  post_tasks:
    - name: Nat mag nooit default route zijn
      shell: nmcli connection modify eth0 ipv4.never-default yes
    - name: Default route over host only adapter instellen
      shell: nmcli connection modify System\ eth1 ipv4.routes 192.0.2.0/24 ipv4.gateway 192.0.2.254
    - name: dns uitschakelen op nat
      shell: nmcli connection modify eth0 +ipv4.ignore-auto-dns true
    - name: dns inschakelen via de router
      shell: nmcli connection modify System\ eth1 ipv4.dns "192.0.2.10 192.0.2.254"
    - name: search domein instellen
      shell: nmcli connection modify System\ eth1 ipv4.dns-search avalon.lan
    - name: Restart network service
      systemd:
       name: network.service
       state: restarted

- hosts: pr001
  become: true
  roles: [bertvv.rh-base,bertvv.dhcp]
  post_tasks:
    - name: Nat mag nooit default route zijn
      shell: nmcli connection modify eth0 ipv4.never-default yes
    - name: Default route over host only adapter instellen
      shell: nmcli connection modify System\ eth1 ipv4.routes 172.16.0.0/16 ipv4.gateway 172.16.255.254
    - name: dns uitschakelen op nat
      shell: nmcli connection modify eth0 +ipv4.ignore-auto-dns true
    - name: dns inschakelen via de router
      shell: nmcli connection modify System\ eth1 ipv4.dns "192.0.2.10 172.16.255.254"
    - name: search domein instellen
      shell: nmcli connection modify System\ eth1 ipv4.dns-search avalon.lan
    - name: Restart network service
      systemd:
       name: network.service
       state: restarted


- hosts: pr011
  become: true
  roles: [bertvv.rh-base,bertvv.samba,bertvv.vsftpd]
  post_tasks:
    - name: Nat mag nooit default route zijn
      shell: nmcli connection modify eth0 ipv4.never-default yes
    - name: Default route over host only adapter instellen
      shell: nmcli connection modify System\ eth1 ipv4.routes 172.16.0.0/16 ipv4.gateway 172.16.255.254
    - name: dns uitschakelen op nat
      shell: nmcli connection modify eth0 +ipv4.ignore-auto-dns true
    - name: dns inschakelen via de router
      shell: nmcli connection modify System\ eth1 ipv4.dns "192.0.2.10 172.16.255.254"
    - name: search domein instellen
      shell: nmcli connection modify System\ eth1 ipv4.dns-search avalon.lan
    - name: Restart network service
      systemd:
       name: network.service
       state: restarted

- hosts: client
  become: true
  roles:
    - bertvv.rh-base
  post_tasks:
    - name: Nat mag nooit default route zijn
      shell: nmcli connection modify eth0 ipv4.never-default yes
    - name: Default route over host only adapter instellen
      shell: nmcli connection modify System\ eth1 ipv4.routes 192.0.2.0/24 ipv4.gateway 192.0.2.254
    - name: dns uitschakelen op nat
      shell: nmcli connection modify eth0 +ipv4.ignore-auto-dns true
    - name: dns inschakelen via de router
      shell: nmcli connection modify System\ eth1 ipv4.dns "192.0.2.10 192.0.2.254"
    - name: search domein instellen
      shell: nmcli connection modify System\ eth1 ipv4.dns-search avalon.lan
    - name: Restart network service
      systemd:
       name: network.service
       state: restarted

